import {ErrorMessageMap, ErrorMessageTranslator} from './components/errormessageoverlay';
import {ErrorEvent} from 'bitmovin-player';

export namespace ErrorUtils {

    export const defaultErrorMessages: ErrorMessageMap = {
        1000: 'Error is unknown',
        1001: 'The player API is not available after a call to PlayerAPI.destroy.',
        1100: 'General setup error',
        1101: 'There was an error when inserting the HTML video element',
        1102: 'No configuration was provided',
        1103: 'The license is not valid',
        1104: 'The the domain-locked player is not authorized to playback on this domain',
        1105: 'The domain is not whitelisted',
        1106: 'The license server URL is invalid',
        1107: 'The impression server URL is invalid',
        1108: 'Could not initialize a rendering engine',
        1109: 'The used flash version does not support playback',
        1110: 'Native Flash is not authorized by a valid Adobe token',
        1111: 'Flash doesn\'t have sufficient resources',
        1112: 'Flash container API not available',
        1113: 'Protocol not supported. This site has been loaded using "file" protocol, but unfortunately this is not supported. Please load the page using a web server (using http or https)',
        1200: 'General source error',
        1201: 'No valid source was provided',
        1202: 'The downloaded manifest is invalid',
        1203: 'There was no technology detected to playback the provided source',
        1204: 'The stream type is not supported',
        1205: 'The forced technology is not supported',
        1206: 'No stream found for supported technologies.',
        1207: 'The downloaded segment is empty',
        1208: 'The manifest could not be loaded',
        1209: 'Progressive stream type not supported or the stream has an error',
        1210: 'HLS stream has an error',
        1211: 'The encryption method is not supported',
        1300: 'General playback error',
        1301: 'Video decoder or demuxer had an error with the content',
        1302: 'General error if Flash renderer has an error',
        1303: 'Flash doesn\'t have sufficient resources',
        1304: 'The transmuxer could not be initialized',
        1400: 'Network error while downloading',
        1401: 'The manifest download timed out',
        1402: 'The segment download timed out',
        1403: 'The progressive stream download timed out',
        1404: 'The Certificate could not be loaded',
        2000: 'General DRM error',
        2001: 'Required DRM configuration is missing',
        2002: 'The licensing server URL is missing',
        2003: 'License request failed',
        2004: 'Key or KeyId is missing',
        2005: 'Key size is not supported',
        2006: 'Unable to instantiate a key system supporting the required combinations',
        2007: 'Unable to create or initialize key session',
        2008: 'The MediaKey object could not be created/initialized',
        2009: 'Key error',
        2010: 'The key system is not supported',
        2011: 'The certificate is not valid',
        2012: 'Invalid header key/value pair for PlayReady license request',
        2013: 'Content cannot be played back because the output is restricted on this machine',
        2014: 'DRM error for the Flash renderer',
        2100: 'General VR error',
        2101: 'Player technology not compatible with VR playback',
        3000: 'General module error',
        3001: 'The definition of the module is invalid (e.g. incomplete).',
        3002: 'The module definition specifies dependencies but the module is not provided via a function for deferred loading.',
        3003: 'A module cannot be loaded because it has not been added to the player core.',
        3004: 'A module cannot be loaded because one or more dependencies are missing.',
        3100: 'An Advertising module error has occurred. Refer to the attached AdvertisingError.',
        3005: 'No URL to manifest given',
        3006: 'Could not load manifest, got HTTP status code ',
        3011: 'DRM: License request failed with HTTP status ',
        3012: 'DRM: Invalid header name/value pair for PlayReady license request',
        3013: 'DRM: Key or KeyID is missing',
        3014: 'DRM: Key size not supported',
        3016: 'DRM: Unable to instantiate a key system supporting the required combinations',
        3017: 'DRM: Unable to create or initialize key session',
        3018: 'DRM: Failed to create and initialize a MediaKeys object',
        3019: 'DRM: Certificate request failed with HTTP status ',
        3020: 'DRM: Key Error',
        3021: 'DRM: Key System not supported',
        3022: 'Error with the manifest, maybe MPD is not valid',
        3023: '<strong>A network error occurred. The reason might be:</strong><br><ul><li>No Internet connection</li><li>Domain Name could not be resolved</li><li>The server refused the connection</li><li>CORS is not enabled</li> </ul>',
        3024: 'Manifest download has timed out',
        3025: 'Segment download has timed out',
        3026: 'Progressive stream has timed out',
        3027: 'DRM: Certificate Error',
        3028: 'Progressive stream type not supported or the stream has an error',
        3029: 'HLS stream has an error',
        3030: 'Could not skip gap',
        3031: 'DRM: Could not parse Fairplay certificate',
        3032: 'No supported source found within manifest',
        3033: 'DRM: License server URL not found (LA_URL, getLicenseServerUrl or manifest)',
        3034: 'DRM: No DRM configuration provided for protected stream',
        3035: 'Player had too many consecutive errors',
        3036: 'DRM: Content cannot be played back because the output is restricted on this machine',
        3037: 'The manifest response was empty.',
        3038: 'The manifest is not valid XML.',
        3039: 'The Smooth Streaming Manifest file does not contain a required SmoothStreamingMedia root element',
        3040: 'Unknown media type: ',
        3041: 'Could not find a SmoothStreaming StreamIndex matching the current representation. Unable to generate init segment.',
        3042: 'Data segment does not contain a mandatory tfdt box',
        3043: 'Unable to parse H264-codec information from CodecPrivateData',
        3044: 'Unable to find a matching Smooth QualityInformation for the current representation',
        3045: 'Missing fragment information in the Manifest.',
        3046: 'Invalid smooth streaming manifest. There is a StreamFragment Element without duration and without start positions of previous/next StreamFragments to calculate it.',
        3047: 'HLS: Encryption method {{encryption-method}} not supported in HTML5 (MSE-based) player',
        3048: 'Could not load transmuxer',
        3049: 'DRM: No init data for key system {{key-system}} found.',
        1003: 'No source was provided',
        1004: 'There was an error when inserting the HTML video element',
        1005: 'An error occurred during creating the flash player',
        1008: 'This player is domain-locked, but the current domain is not whitelisted.',
        1009: 'Could not load skin, using the default player skin',
        1010: 'Protocol not supported. This site has been loaded using "file" protocol, but unfortunately this is not supported. Please load the page using a web server (using http or https)',
        1011: 'No configuration was provided',
        1013: 'Unsupported stream type',
        1014: 'Unknown player type',
        1015: 'The player you tried to force ({{player-type}}) is not supported.',
        1016: '<strong>License Error</strong></br> {{error-message}}',
        1017: '<strong>License Error</strong></br> {{error-message}} </br> Please whitelist this domain in the backend.',
        1018: 'Invalid license server url ({{license-server}})',
        1019: 'Invalid impression server url ({{impression-server}})',
        1020: 'No supported VR source was found',
        1021: 'Player technology not compatible with VR playback',
        1022: 'Browser does not support important array objects',
        1023: 'No stream found for supported technologies.',
        1024: 'No rendering engine given',
        1025: 'Player is already set up',
        1026: 'Could not load VR library',
        1027: 'Player is not set up',
        1028: 'HLS manifest URL needs to be a string',
        5001: 'Maximum number of retries exceeded, {{mime-type}} stream seems finished or has a problem',
        5002: 'Unsupported codec and/or file format for stream {{mime-type}}',
        5003: 'Could not load subtitles/captions, got HTTP status code ',
        5004: 'Could not decrypt segment',
        5005: 'Could not load Google IMA SDK',
        5006: 'VR Rendering error: ',
        5007: 'Native HLS query parameters not available',
        5008: 'Playback could not be started, reason: ',
        5009: 'Unknown codec in SmoothStreaming manifest: ',
        5010: 'No representation provided, can not generate an init segment',
        5011: 'Tried to create an init segment before the SmoothManifest was parsed.',
        5012: 'Encountered negative DTS {{segment-playback-time}} for {{mime-type}} segment ({{segment-url}}), attempting to correct PTO...',
        5013: 'Could not load manifest, got HTTP status code ',
        5014: 'Missing Module: ',
        5015: 'DRM: Content Decryption Module (CDM) does not support server certificates',
    };

    export const defaultErrorMessageTranslator: ErrorMessageTranslator = (error: ErrorEvent) => {
        const errorMessage = ErrorUtils.defaultErrorMessages[error.code];

        if (errorMessage) {
            let name = '';
            if (error.name) {
                name = `${error.name} [${error.code}]`;
            } else {
                name = `${error.code}`;
            }
            // Use the error message text if there is one
            return `${errorMessage}\n(${name})`; // default error message style
        } else {
            // Fallback to error code/name if no message is defined
            return `${error.code} ${error.name}`;
        }
    };
}
